/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZekmanageRouteImport } from './routes/zekmanage'
import { Route as ZekleaseRouteImport } from './routes/zeklease'
import { Route as WhyZekanoRouteImport } from './routes/why-zekano'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'
import { Route as StewardshipRouteImport } from './routes/stewardship'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as OurSystemsRouteImport } from './routes/our-systems'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as OurPrinciplesRouteImport } from './routes/our-principles'
import { Route as OurPhilosophyRouteImport } from './routes/our-philosophy'
import { Route as OurCultureRouteImport } from './routes/our-culture'
import { Route as OurCommitmentRouteImport } from './routes/our-commitment'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const ZekmanageRoute = ZekmanageRouteImport.update({
  id: '/zekmanage',
  path: '/zekmanage',
  getParentRoute: () => rootRouteImport,
} as any)
const ZekleaseRoute = ZekleaseRouteImport.update({
  id: '/zeklease',
  path: '/zeklease',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyZekanoRoute = WhyZekanoRouteImport.update({
  id: '/why-zekano',
  path: '/why-zekano',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const StewardshipRoute = StewardshipRouteImport.update({
  id: '/stewardship',
  path: '/stewardship',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const OurSystemsRoute = OurSystemsRouteImport.update({
  id: '/our-systems',
  path: '/our-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const OurPrinciplesRoute = OurPrinciplesRouteImport.update({
  id: '/our-principles',
  path: '/our-principles',
  getParentRoute: () => rootRouteImport,
} as any)
const OurPhilosophyRoute = OurPhilosophyRouteImport.update({
  id: '/our-philosophy',
  path: '/our-philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurCultureRoute = OurCultureRouteImport.update({
  id: '/our-culture',
  path: '/our-culture',
  getParentRoute: () => rootRouteImport,
} as any)
const OurCommitmentRoute = OurCommitmentRouteImport.update({
  id: '/our-commitment',
  path: '/our-commitment',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/our-commitment': typeof OurCommitmentRoute
  '/our-culture': typeof OurCultureRoute
  '/our-philosophy': typeof OurPhilosophyRoute
  '/our-principles': typeof OurPrinciplesRoute
  '/our-story': typeof OurStoryRoute
  '/our-systems': typeof OurSystemsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stewardship': typeof StewardshipRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/why-zekano': typeof WhyZekanoRoute
  '/zeklease': typeof ZekleaseRoute
  '/zekmanage': typeof ZekmanageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/our-commitment': typeof OurCommitmentRoute
  '/our-culture': typeof OurCultureRoute
  '/our-philosophy': typeof OurPhilosophyRoute
  '/our-principles': typeof OurPrinciplesRoute
  '/our-story': typeof OurStoryRoute
  '/our-systems': typeof OurSystemsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stewardship': typeof StewardshipRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/why-zekano': typeof WhyZekanoRoute
  '/zeklease': typeof ZekleaseRoute
  '/zekmanage': typeof ZekmanageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/our-commitment': typeof OurCommitmentRoute
  '/our-culture': typeof OurCultureRoute
  '/our-philosophy': typeof OurPhilosophyRoute
  '/our-principles': typeof OurPrinciplesRoute
  '/our-story': typeof OurStoryRoute
  '/our-systems': typeof OurSystemsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stewardship': typeof StewardshipRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/why-zekano': typeof WhyZekanoRoute
  '/zeklease': typeof ZekleaseRoute
  '/zekmanage': typeof ZekmanageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/company'
    | '/contact'
    | '/leadership'
    | '/our-commitment'
    | '/our-culture'
    | '/our-philosophy'
    | '/our-principles'
    | '/our-story'
    | '/our-systems'
    | '/resources'
    | '/sitemap.xml'
    | '/stewardship'
    | '/what-we-do'
    | '/why-zekano'
    | '/zeklease'
    | '/zekmanage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/company'
    | '/contact'
    | '/leadership'
    | '/our-commitment'
    | '/our-culture'
    | '/our-philosophy'
    | '/our-principles'
    | '/our-story'
    | '/our-systems'
    | '/resources'
    | '/sitemap.xml'
    | '/stewardship'
    | '/what-we-do'
    | '/why-zekano'
    | '/zeklease'
    | '/zekmanage'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/company'
    | '/contact'
    | '/leadership'
    | '/our-commitment'
    | '/our-culture'
    | '/our-philosophy'
    | '/our-principles'
    | '/our-story'
    | '/our-systems'
    | '/resources'
    | '/sitemap.xml'
    | '/stewardship'
    | '/what-we-do'
    | '/why-zekano'
    | '/zeklease'
    | '/zekmanage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  LeadershipRoute: typeof LeadershipRoute
  OurCommitmentRoute: typeof OurCommitmentRoute
  OurCultureRoute: typeof OurCultureRoute
  OurPhilosophyRoute: typeof OurPhilosophyRoute
  OurPrinciplesRoute: typeof OurPrinciplesRoute
  OurStoryRoute: typeof OurStoryRoute
  OurSystemsRoute: typeof OurSystemsRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StewardshipRoute: typeof StewardshipRoute
  WhatWeDoRoute: typeof WhatWeDoRoute
  WhyZekanoRoute: typeof WhyZekanoRoute
  ZekleaseRoute: typeof ZekleaseRoute
  ZekmanageRoute: typeof ZekmanageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zekmanage': {
      id: '/zekmanage'
      path: '/zekmanage'
      fullPath: '/zekmanage'
      preLoaderRoute: typeof ZekmanageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zeklease': {
      id: '/zeklease'
      path: '/zeklease'
      fullPath: '/zeklease'
      preLoaderRoute: typeof ZekleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-zekano': {
      id: '/why-zekano'
      path: '/why-zekano'
      fullPath: '/why-zekano'
      preLoaderRoute: typeof WhyZekanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stewardship': {
      id: '/stewardship'
      path: '/stewardship'
      fullPath: '/stewardship'
      preLoaderRoute: typeof StewardshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-systems': {
      id: '/our-systems'
      path: '/our-systems'
      fullPath: '/our-systems'
      preLoaderRoute: typeof OurSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-principles': {
      id: '/our-principles'
      path: '/our-principles'
      fullPath: '/our-principles'
      preLoaderRoute: typeof OurPrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-philosophy': {
      id: '/our-philosophy'
      path: '/our-philosophy'
      fullPath: '/our-philosophy'
      preLoaderRoute: typeof OurPhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-culture': {
      id: '/our-culture'
      path: '/our-culture'
      fullPath: '/our-culture'
      preLoaderRoute: typeof OurCultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-commitment': {
      id: '/our-commitment'
      path: '/our-commitment'
      fullPath: '/our-commitment'
      preLoaderRoute: typeof OurCommitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  LeadershipRoute: LeadershipRoute,
  OurCommitmentRoute: OurCommitmentRoute,
  OurCultureRoute: OurCultureRoute,
  OurPhilosophyRoute: OurPhilosophyRoute,
  OurPrinciplesRoute: OurPrinciplesRoute,
  OurStoryRoute: OurStoryRoute,
  OurSystemsRoute: OurSystemsRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StewardshipRoute: StewardshipRoute,
  WhatWeDoRoute: WhatWeDoRoute,
  WhyZekanoRoute: WhyZekanoRoute,
  ZekleaseRoute: ZekleaseRoute,
  ZekmanageRoute: ZekmanageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
