/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZekmanageRouteImport } from './routes/zekmanage'
import { Route as ZekleaseRouteImport } from './routes/zeklease'
import { Route as WhyZekanoRouteImport } from './routes/why-zekano'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as OurSystemsRouteImport } from './routes/our-systems'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as IndexRouteImport } from './routes/index'

const ZekmanageRoute = ZekmanageRouteImport.update({
  id: '/zekmanage',
  path: '/zekmanage',
  getParentRoute: () => rootRouteImport,
} as any)
const ZekleaseRoute = ZekleaseRouteImport.update({
  id: '/zeklease',
  path: '/zeklease',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyZekanoRoute = WhyZekanoRouteImport.update({
  id: '/why-zekano',
  path: '/why-zekano',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const OurSystemsRoute = OurSystemsRouteImport.update({
  id: '/our-systems',
  path: '/our-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/our-story': typeof OurStoryRoute
  '/our-systems': typeof OurSystemsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/why-zekano': typeof WhyZekanoRoute
  '/zeklease': typeof ZekleaseRoute
  '/zekmanage': typeof ZekmanageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/our-story': typeof OurStoryRoute
  '/our-systems': typeof OurSystemsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/why-zekano': typeof WhyZekanoRoute
  '/zeklease': typeof ZekleaseRoute
  '/zekmanage': typeof ZekmanageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/our-story': typeof OurStoryRoute
  '/our-systems': typeof OurSystemsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/why-zekano': typeof WhyZekanoRoute
  '/zeklease': typeof ZekleaseRoute
  '/zekmanage': typeof ZekmanageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/contact'
    | '/our-story'
    | '/our-systems'
    | '/resources'
    | '/sitemap.xml'
    | '/what-we-do'
    | '/why-zekano'
    | '/zeklease'
    | '/zekmanage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/contact'
    | '/our-story'
    | '/our-systems'
    | '/resources'
    | '/sitemap.xml'
    | '/what-we-do'
    | '/why-zekano'
    | '/zeklease'
    | '/zekmanage'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/contact'
    | '/our-story'
    | '/our-systems'
    | '/resources'
    | '/sitemap.xml'
    | '/what-we-do'
    | '/why-zekano'
    | '/zeklease'
    | '/zekmanage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  OurStoryRoute: typeof OurStoryRoute
  OurSystemsRoute: typeof OurSystemsRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhatWeDoRoute: typeof WhatWeDoRoute
  WhyZekanoRoute: typeof WhyZekanoRoute
  ZekleaseRoute: typeof ZekleaseRoute
  ZekmanageRoute: typeof ZekmanageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zekmanage': {
      id: '/zekmanage'
      path: '/zekmanage'
      fullPath: '/zekmanage'
      preLoaderRoute: typeof ZekmanageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zeklease': {
      id: '/zeklease'
      path: '/zeklease'
      fullPath: '/zeklease'
      preLoaderRoute: typeof ZekleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-zekano': {
      id: '/why-zekano'
      path: '/why-zekano'
      fullPath: '/why-zekano'
      preLoaderRoute: typeof WhyZekanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-systems': {
      id: '/our-systems'
      path: '/our-systems'
      fullPath: '/our-systems'
      preLoaderRoute: typeof OurSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  OurStoryRoute: OurStoryRoute,
  OurSystemsRoute: OurSystemsRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhatWeDoRoute: WhatWeDoRoute,
  WhyZekanoRoute: WhyZekanoRoute,
  ZekleaseRoute: ZekleaseRoute,
  ZekmanageRoute: ZekmanageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
